# Generated by Django 3.2.5 on 2021-07-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pais')),
                ('nombrePais', models.CharField(max_length=50, verbose_name='Nombre del Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('identificacion', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numero de Identificacion')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
    ]
